Shougo/ddc.vim

.github/workflows/deno.yml

ローカルで実行できる[nektos/act](https://github.com/nektos/act)で確認しました。
* ubuntu-latestに
* あまりjobを細切れにするのもcloneとか環境用意とかもったいないかと思ったのでlint, testの2構成に
- 1回の実行で悪いとこ全部知りたさもある
* `denops/**/*.ts`をfindにした
- https://github.com/Shougo/ddc.vim/runs/2928558212 を見るに
denops/ddc/直下の4ファイルしかチェックされていないので
`denops/**/*.ts`は`denops/*/*.ts`として処理されている気がする
* 全ファイルをtestにかけると遅いので"Deno.test"があるファイルだけtestにかけるようにした
* vintはディレクトリ2つ渡しても動いてくれた

github actions

---

README.md

There is a syntax error in the configuration example written in README.md.
Specifically, the quotation marks are not closed.
more info.
see [https://github.com/Shougo/ddc.vim/issues/5](https://github.com/Shougo/ddc.vim/issues/5)

fix issue #5

---

Makefile
denops/ddc/app.ts
denops/ddc/base/filter.ts
denops/ddc/ddc.ts
denops/ddc/filters/matcher_head.ts
denops/ddc/types.ts

* add `format` to Makefile
- It's inconvenient to only check format and not know how to do format
* create {Filter,Source}Arg for register{Filter,Source}
- It is defined by ddc, so it can be typed
- `as FilterArg` will convince the type system, but will not be validated
- But `ensureObject as Record<string, unknown>` also returns undefined if the key is missing, so there is no difference
* remove candidates from Context
- It is difficult to make sense of the `context.candidates` during source processing
- Since we're using the strong word Context, it's probably easier to handle something that won't change during the entire process from start
- It would be inconvenient to change to stream
- Filter now explicitly takes candidates and returns candidates
* …

Remove candidates from Context

---

denops/ddc/context.ts
denops/ddc/ddc.ts

* `FiltersUsed`を廃止した
-`filterCandidate`にはsourceOptionsを解体して渡したかったが`FiltersUsed`以外にも必要なoptionsがあるようなのでsourceOptionsを渡す元の形に戻した
* options追加でテストの書き換えを必要とするのは無理があったのでdefaultを使うようにした

`filterCandidates`は`SourceOptions`を必要とする

---

denops/ddc/ddc.ts
denops/ddc/deps.ts
denops/ddc/sources/around.ts

1. Gather candidates of sources concurrently
2. Improve performance of `around` source by using `batch`
3. Use `Set` to remove duplicated words prior to create candidates of `around` source
It seems `getCompletePosition()` use `-1` as an invalid value thus if a `completePos` of the last source is `-1`, completion die. This behavior is consistent prior to this PR and I'm not sure what is the correct approach to determine `completePos` of the entire completion thus I just keep the previous behavior.

Gather candidates of sources concurrently and improve `around` source as an example `batch` usage

---

denops/ddc/app.ts
denops/ddc/context.ts

* Fix getBuffer
* We can write `as Promise<concrete type>`
```
const enabledEskk = (await fn.exists(denops, "*eskk#is_enabled") &&
denops.call("eskk#is_enabled"));
```
Have you checked the type and operator binding order? I don't have any reason to believe it, but it seemed suspicious to me.

Fix getBuffer

---

denops/ddc/context.ts

aroundはpythonのrangeが欲しかったが、こちらはitertoolsが依存にあったら便利だなくらいのもので配列のreduceで十分

Array.prototype.reduce

---

denops/ddc/ddc.ts

string.search() returns -1 on no match.

Fix check of return value of search()

---

denops/ddc/app.ts
denops/ddc/base/filter.ts
denops/ddc/base/source.ts
denops/ddc/ddc.ts

I'm creating [buffer source](https://github.com/matsui54/ddc-buffer) and this source's cache should be made on autocmd-events other than InsertEnter.
In this PR, I tried to enable selecting whatever autocmds-events that sources and filters need.

Enable selecting autocmds for onEvent() of sources and filters

---

denops/ddc/ddc.ts

When input pattern doesn't match keywordPattern but matches forceCompletionPattern, completion menu doesn't appear because completePos is -1.
In this case, completion menu must appear next to the cursor posision.

Fix completePos when forceCompletion

---

denops/ddc/context.ts
denops/ddc/util.ts

`:help 'iskeyword'` says:
> See 'isfname' for a description of the format of this option.
And `:help 'isfname'` says:
> If the character is '@', all characters where isalpha() returns TRUE
> are included.  Normally these are the characters a to z and A to Z,

Fix conversion of iskeyword in keywordPattern

---

denops/ddc/base/filter.ts
denops/ddc/base/source.ts
denops/ddc/ddc.ts
denops/ddc/types.ts
doc/ddc.txt

Related: https://github.com/Shougo/ddc.vim/pull/46, https://github.com/Shougo/ddc.vim/pull/52
I'll add comments to describe some of my decisions.
```ts
// -----------------------------------------------------------------
// source
// -----------------------------------------------------------------
// optional, but required when using UserData.
// User can skip defining by Params = {} or Params = Record<string, unknown>
type Params = {
myParam: number
}
type UserData = {
myData: string;
}
class MySource extends BaseSource<Params, UserData> {
async gatherCandidates() {
return [
{
word: "a",
user_data: {
myData: "data",
// type error
// myData: 3
// Prevented by type checking even if defined in UserData.
// type error
// __sourceName: "data",
},
},
]
}
params() {
return {
myParam: 3
// type …
```

Add type parameters for classes extended by users.

---

denops/ddc/app.ts
denops/ddc/context.ts
denops/ddc/types.ts
doc/ddc.txt

- Add `backspaceCompletion` option which enables us to be able to make `ddc.vim` complete even when `backspace` will be typed.
- Even though the backspace completion causes the completion flicker, I'd like to make `ddc.vim` automatically complete when the backspace key is typed without the extra typing.
Is this kind of control capability for the backspace completion acceptable...?

Add backspaceCompletion option

---

denops/ddc/ddc.ts

to solve the problem that sources aliased not to be loaded
short repro:
```
call ddc#custom#alias('source', 'around2', 'around')
call ddc#custom#patch_global('sources', ['around2'])
```
-> nothing is loaded.
this comes from `e82874f58d268d0b4dd0425285f09c1f165d4d33`
thank you.

fix: load alias resolved name

---

denops/ddc/ddc.ts

In TypeScript, array comparison *always* returns `false`:
```ts
> ["foo"] == ["foo"]
false
> ["foo"] === ["foo"]
false
```
The branches are hence unreachable without the modification.

fix: use `JSON.stringify` for array comparison

---

denops/ddc/ddc.ts

Currently filter.onInit() was called two times.
https://github.com/Shougo/ddc.vim/blob/f2ec802e9cc8bb0d94fcbff6de29b736bc904944/denops/ddc/ddc.ts#L136
https://github.com/Shougo/ddc.vim/blob/f2ec802e9cc8bb0d94fcbff6de29b736bc904944/denops/ddc/ddc.ts#L712
This PR is delete first call because I thought forgotten to delete that.

Fix filter.onInit() was duplicate called

---

denops/ddc/app.ts
denops/ddc/context.ts

Probrem is that `onEvent()` isn't always called on some events when the `World` is the same.
For example, `InsertLeave` event isn't called, because the `input` is the same, which means the `World` is the same.
All events must always be called.

Ensure onEvent() is always called.

---

autoload/ddc.vim

When using ddc.vim in search command line with `'incsearch'` on, sometimes completion menu doesn't appear.
Return value of `virtcol()` can be cursor position in normal mode when `'incsearch'` is on, so use `getcmdpos()` instead.

Use getcmdpos() for getting column in command line

---

denops/ddc/base/source.ts
denops/ddc/ddc.ts

If intended, it's ok.
When users want to specify `('")(?:.(?!\1))*` for `forceCompletionPattern`, as it denotes _yet closed string literals_, this should be passed as `('")(?:(?!\2))`, as group numbers are counted up by 1.
The problem is that users can't intuitively use theses options with capturing.

Prevent JS RegExp counting capture group number to make it fully controllable for users

---

denops/ddc/base/source.ts
denops/ddc/ddc.ts
denops/ddc/types.ts

Lsp candidates is sometimes incomplete, which means all candidates are not sent from lsp server.
For example, if you set `'forceCompletionPattern': "<"` and type `#include <` in C files, you can see some include files, but if you type more word to narrow down the candidates, you will notice that not all candidates are shown. In the gif, I want to select `string.h`, but there isn't such file.
This problem occurs in both ddc-nvim-lsp and ddc-vim-lsp.
This problem is caused by the specification of lsp.
As shown [here](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#completionList), when `CompletionList.isIncomplete == true`, the candidates sent from the lsp server is incomplete. Therefore, we need to send `textDocument/completion` request again when …

Support incomplete items of LSP server

---

doc/ddc.txt

helptagsが重複していました。
最近のコミットした方を残しました。
いま残ってる方が`ddc#custom#set_global()`のヘルプの修正版でしょうか？
よろしければ、マージお願いします。

Fix duplicate helptags.

---

denops/ddc/context.ts

When used with [kana/vim-smartinput](https://github.com/kana/vim-smartinput) and [kana/vim-smartchr](https://github.com/kana/vim-smartchr) in the following configuration, completion of structure members, etc. may not be displayed.
<details>
<summary>minimal.vim</summary>
```vim
let plugins = [
\ "/home/erw7/.config/nvim/dein/repos/github.com/vim-denops/denops.vim",
\ "/home/erw7/.config/nvim/dein/repos/github.com/Shougo/ddc.vim",
\ "/home/erw7/.config/nvim/dein/repos/github.com/Shougo/ddc-nvim-lsp",
\ "/home/erw7/.config/nvim/dein/repos/github.com/Shougo/ddc-sorter_rank",
\ "/home/erw7/.config/nvim/dein/repos/github.com/Shougo/ddc-matcher_head",
\ "/home/erw7/.config/nvim/dein/repos/github.com/neovim/nvim-lspconfig",
\ "/home/erw7/.config/nvim/dein/repos/github.com/kana/vim-smartinput",
\ …
```

fix completion problems that occur in some case

---

autoload/ddc.vim

The custom parameters will be kept even after the second restart.
The custom parameters is empty when denops.vim is restarted twice.
Keep the custom parameters.
vimrc
```vim
" minimum vimrc
set nocompatible
set rtp^=path/to/denops.vim
set rtp^=path/to/ddc.vim
call ddc#custom#patch_global('autoCompleteDelay', 42)
call ddc#enable()
" testing
autocmd VimEnter * call timer_start(3000, funcref('Test'))
function! Test(...) abort
echom "0:" ddc#custom#get_global()
call denops#server#restart()
call timer_start(3000, funcref('Test1'))
endfunction
function! Test1(...) abort
echom "1:" ddc#custom#get_global()
call denops#server#restart()
call timer_start(3000, funcref('Test2'))
endfunction
function! Test2(...) abort
echom "2:" ddc#custom#get_global()
endfunction
```
Run `vim -u testvimrc`.
Show …

fix: keep custom parameters when restart multiple times

---

autoload/ddc.vim

There are cases where the error message "No matching autocommands" is shows.
So I added a placeholder for the autocommand.
I rejected the method of adding `silent` to `doautocmd` because it has side effects.
Or there was a way to check with `exists()`, but I chose this simple implementation.
The following error message is shows.
```
No matching autocommands: User DDCReady
```
No error message is shows.
*testvimrc*
```vim
set nocompatible
set rtp^=path/to/denops.vim
set rtp^=path/to/ddc.vim
call ddc#enable()
```
Run `vim -u testvimrc`.

fix: suppress error of no matching autocommands

---

autoload/ddc.vim

Always add a register call to `DenopsReady`.
If `ddc#enable()` is called after `DenopsReady`, ddc is not enabled after denops server restart.
Re-enable ddc.
vimrc
```vim
" minimum vimrc
set nocompatible
set rtp^=path/to/denops.vim
set rtp^=path/to/ddc.vim
autocmd User DenopsReady ++once call ddc#enable()
" instead :call ddc#enable()
" testing
augroup testing
autocmd!
autocmd User DDCReady echomsg "[DDCReady fired]"
augroup END
autocmd VimEnter * call timer_start(3000, { -> denops#server#restart() })
```
Run `vim -u vimrc`.
Show result `:messages`.
```
[DDCReady fired]
[denops] Server stopped (-1). Restarting...
[denops] Server is restarted.
```
Expected result.
```
[DDCReady fired]
[denops] Server stopped (-1). Restarting...
[denops] Server is restarted.
[DDCReady fired]
```

fix: register on server restarted even if enabled after DenopsReady

---

denops/ddc/util.ts

Add bufnr argument as needed by plugins that collect keywords from multiple buffers.

Add bufnr argument to `convertKeywordPattern`

---

denops/ddc/app.ts
denops/ddc/ddc.ts

Wasn't apply params/options of `sourceOptions.sources` if source definition is object.
Passing params/options to onCompleteDone arguments. For example in this case display test object.
- ddc.vim version(SHA1): 6c1de37d138d376326c9bbc1ed0b66d6a244189a
- OS: Arch Linux
- neovim/Vim `:version` output:
```
NVIM v0.10.0-dev-672+g33e1a8cd7-dirty
Build type: Debug
LuaJIT 2.1.0-beta3
```
```vim
set rtp+=/data/vim/repos/github.com/vim-denops/denops.vim
set rtp+=/data/vim/repos/github.com/Shougo/ddc.vim
set rtp+=/data/vim/repos/github.com/Shougo/ddc-ui-native
set noshowmode
call ddc#enable()
call ddc#register('source', expand('<sfile>:h') .. '/a.ts')
call ddc#custom#patch_global(#{
\   sources: [
\     #{
\       name: 'a',
\       params: #{
\         test: 'test',
\       },
\     },
\   ],
\ …
```

fix: wasn't consider `sourceOptions.sources` is object at onCompleteDone

---

denops/ddc/context.ts

patchGlobal以外のcmdlineSourcesが無視されていたようなので修正しました。

fix: can't apply `cmdlineSources` of local context

---

.github/workflows/jsr.yml
README.md
deno.jsonc
denops/@ddu-sources/ddc.ts
denops/ddc/app.ts
denops/ddc/base/config.ts
denops/ddc/base/filter.ts
denops/ddc/base/source.ts
denops/ddc/base/ui.ts
denops/ddc/callback.ts
denops/ddc/context.ts
denops/ddc/ddc.ts
denops/ddc/deps.ts
denops/ddc/ext.ts
denops/ddc/loader.ts
denops/ddc/types.ts
denops/ddc/utils.ts
doc/ddc.txt

Migrate to JSR

---

denops/ddc/app.ts
denops/ddc/base/config.ts
denops/ddc/base/filter.ts
denops/ddc/base/source.ts
denops/ddc/base/ui.ts
denops/ddc/context.ts
denops/ddc/ddc.ts
denops/ddc/ext.ts
denops/ddc/loader.ts
denops/ddc/types.ts

- Stop re-exporting `Base*` classes in types.ts
- Unify `Base*Params` types to `BaseParams`
- Remove `loader` property from arguments of methods of `BaseSource`
- Split `ContextBuilder` type definition and implemention
Dependencies Graph:
Size reduction:
```console
$ deno info jsr:@shougo/ddc-vim@6.0.1/types | head -5
local: /Users/user/Library/Caches/deno/deps/https/jsr.io/a590a33b9a7e50e59f7ff1b4f3d8c9586c79b6750e94952894e3cc43c1d70844
emit: /Users/user/Library/Caches/deno/gen/https/jsr.io/a590a33b9a7e50e59f7ff1b4f3d8c9586c79b6750e94952894e3cc43c1d70844.js
type: TypeScript
dependencies: 292 unique
size: 1.93MB
$ deno info denops/ddc/types.ts | head -5
local: /Users/user/Library/Develops/github.com/4513ECHO/ddc.vim/denops/ddc/types.ts
type: TypeScript
dependencies: 10 unique
size: 26.5KB …
```

[WIP] Resolve circular reference

---

denops/ddc/ddc.ts

- Fix potential issue where `completeStr` could have unexpected value when `completePos` is negative
- When `completePos < 0`, set `completeStr` to empty string instead of using slice with negative index
Previously, when `completePos` was negative, `context.input.slice(completePos)` would return characters from the end of the string due to JavaScript's slice behavior. Although this doesn't affect current behavior (since negative `completePos` causes early return), this change prevents potential future bugs.

Fix completeStr calculation when completePos is negative
